server:
  port: 5009

spring:
  application:
    name: SignUp-Form
  cloud:
    discovery:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    name: registration
    password: root
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
